spring:
  application:
    name: otus-social-network
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_updates: true
        jdbc:
          batch_size: 1000
        generate_statistics: false
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      minimumIdle: 5
      maximumPoolSize: 20
      autoCommit: true
    url: jdbc:postgresql://${DB_URL:localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    dispatch-options-request: true

# Token lifetime in seconds
auth:
  token:
    lifetime: ${AUTH_TOKEN_LIFETIME:1000}

orm:
  enabled: ${ORM_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: "*"