spring:
  application:
    name: otus-social-network
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      ssl:
        enabled: ${REDIS_SSL:false}
      ttl-seconds: ${REDIS_TTL_SECONDS:600}
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 70
      autoCommit: true
      jdbcUrl: jdbc:postgresql://${DB_URL:localhost:5432/postgres}
    url: jdbc:postgresql://${DB_URL:localhost:5432/postgres}
    username: ${DB_USER:tester}
    password: ${DB_PASSWORD:tratata228}
  second-db:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 70
      autoCommit: true
      jdbcUrl: jdbc:postgresql://${DB_SLAVE_URL:localhost:5432/postgres}
    url: jdbc:postgresql://${DB_SLAVE_URL:localhost:5432/postgres}
    username: ${DB_SLAVE_USER:postgres}
    password: ${DB_SLAVE_PASSWORD:postgres024}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  mvc:
    dispatch-options-request: true

# Token lifetime in seconds
auth:
  token:
    lifetime: ${AUTH_TOKEN_LIFETIME:1000}

orm:
  enabled: ${ORM_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback.xml